export const ADD_INGRIDIENTS = 'ADD_INGRIDIENTS';
export const REMOVE_INGRIDIENTS = 'REMOVE_INGRIDIENTS';
export const RESET_INGRIDIENTS = 'RESET_INGRIDIENTS';
export const SET_INGRIDIENTS = 'SET_INGRIDIENTS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
